# Generated by Django 5.1.7 on 2025-09-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_language_customuser_theme_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='theme_preference',
        ),
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
