# Generated by Django 5.1.7 on 2025-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
