# Generated by Django 5.1.7 on 2025-10-05 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lessonmaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrolled_at',
            new_name='date_enrolled',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
