# Generated by Django 5.1.7 on 2025-10-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_lesson_options_remove_lesson_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
