# Generated by Django 5.1.7 on 2025-10-17 04:29

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_enrollment_course_alter_enrollment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='file',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='completion_date',
            field=models.DateField(default=courses.models.default_completion_date),
        ),
    ]
